# 导入所需的库

In [8]:
import pandas as pd
from model_lab.quick_score_card import QuickScoreCard
from numpy import infty

data = pd.read_excel('test_data.xlsx')
data['PassengerId'] = list(range(1, len(data) + 1))
data = data.set_index('PassengerId')

dataset_config = {
    'label_col_name': 'Survived',
    'dataset_col_name': 'dataset_name',
    'train_dataset_name': 'train',
    'test_dataset_names': ['test'],
    'oot_dataset_name': 'oot'
}

auto_binning_config = {
    'bin_max_all': 4,
    'min_sample_n': 100
}

user_config = {
    'Age': {
        'mode': 'manual',
        'keep_values': [],
        'bins': [-infty, 19, 42, infty]
    }
}


trainer = QuickScoreCard(data, dataset_config, auto_binning_config)
trainer.set_features_performance_threshold(0.01, 0.1, 0.1)
trainer.set_corr_threshold_for_model(0.7)
trainer.run()
trainer.display_summary()
trainer.to_excel('test_1')

Doing task encoder_training ...
Doing task feature_importance_analysis ...
Doing task feature_corr_analysis ...
keep features with iv >= 0.01, rate_error_max <= 0.1 and population_psi_max <= 0.1
Doing task model_training ...
Choose woe features pairs with corr higher than 0.7, keep the one with higer iv
Retrain best model with belowing features
['Embarked', 'Fare', 'Parch', 'Pclass', 'Sex', 'SibSp', 'cabin_count']


===== feature binning =====

===== feature performance =====

                  metric_value                                   \
metric_name  negative_dist_psi
                          mean       max       min higher lower
feature_name
Embarked              0.001859  0.001859  0.001859    NaN   NaN
Fare                  0.035857  0.035857  0.035857    NaN   NaN
Parch                 0.010854  0.010854  0.010854    NaN   NaN
Pclass                0.003816  0.003816  0.003816    NaN   NaN
Sex                   0.002710  0.002710  0.002710    NaN   NaN
SibSp                 0.021566  0.021566  0.021566    NaN   NaN
cabin_count           0.012566  0.012566  0.012566    NaN   NaN

                                                              \
metric_name  population_psi
                       mean       max       min higher lower
feature_name
Embarked           0.009302  0.009302  0.009302    NaN   NaN
Fare               0.008308  0.008308  0.008308    NaN   NaN
Parch              0.000028  0.000028  0.000028    NaN   NaN
Pclass             0.000012  0.000012  0.000012    NaN   NaN
Sex                0.003658  0.003658  0.003658    NaN   NaN
SibSp              0.009322  0.009322  0.009322    NaN   NaN
cabin_count        0.006142  0.006142  0.006142    NaN   NaN

                                                                 \
metric_name  positive_dist_psi
                          mean       max       min higher lower
feature_name
Embarked              0.021656  0.021656  0.021656    NaN   NaN
Fare                  0.015847  0.015847  0.015847    NaN   NaN
Parch                 0.026936  0.026936  0.026936    NaN   NaN
Pclass                0.019700  0.019700  0.019700    NaN   NaN
Sex                   0.002706  0.002706  0.002706    NaN   NaN
SibSp                 0.000217  0.000217  0.000217    NaN   NaN
cabin_count           0.044802  0.044802  0.044802    NaN   NaN


metric_name  weighted_rate_error_mse
                                mean       max       min higher lower
feature_name
Embarked                    0.016426  0.016426  0.016426    NaN   NaN
Fare                        0.063330  0.063330  0.063330    NaN   NaN
Parch                       0.064714  0.064714  0.064714    NaN   NaN
Pclass                      0.044909  0.044909  0.044909    NaN   NaN
Sex                         0.003324  0.003324  0.003324    NaN   NaN
SibSp                       0.034944  0.034944  0.034944    NaN   NaN
cabin_count                 0.063385  0.063385  0.063385    NaN   NaN

===== model_performace =====
performance in dataset: train

performance in dataset: test

===== model_vif =====

        column       vif
0     Embarked  1.075861
1         Fare  2.833188
2        Parch  1.353871
3       Pclass  2.079398
4          Sex  1.109649
5        SibSp  1.463746
6  cabin_count  1.596488